# Sidebar navigation
- label: "home"
  link: "/"
- label: AppSheet
  items:
    - label: "AppSheetとはなにか"
      link: "/appsheet/about"
    - label: "習慣化アプリの作り方"
      link: "/appsheet/howto"
    - label: "SQ4Rアプリの作り方"
      link: "/appsheet/sq4r"
    - label: "Spec機能を使った日記アプリの作り方"
      link: "/appsheet/spec"
